export const produtosEstoque = [
  {
    codigo: "PRD-0021",
    nome: "Farinha de Trigo",
    categoria: "Alimentos",
    fornecedor: "Alimentos Silva Ltda",
    preco: "R$ 8,90",
    quantidadePorUnidade: "1 kg",
    dataValidade: "2026-12-15",
  },
  {
    codigo: "PRD-0089",
    nome: "Sabão em Pó",
    categoria: "Limpeza",
    fornecedor: "Clean Maxx",
    preco: "R$ 12,50",
    quantidadePorUnidade: "1 kg",
    dataValidade: "2027-06-01",
  },
  {
    codigo: "PRD-0150",
    nome: "Arroz Branco 5kg",
    categoria: "Alimentos",
    fornecedor: "Cerealista Brasil",
    preco: "R$ 25,00",
    quantidadePorUnidade: "5 kg",
    dataValidade: "2026-11-30",
  },
  {
    codigo: "PRD-0210",
    nome: "Detergente Líquido",
    categoria: "Limpeza",
    fornecedor: "Higiclean",
    preco: "R$ 3,50",
    quantidadePorUnidade: "500 ml",
    dataValidade: "2027-03-20",
  },
  {
    codigo: "PRD-0305",
    nome: "Café Torrado 500g",
    categoria: "Alimentos",
    fornecedor: "Café do Sul",
    preco: "R$ 14,90",
    quantidadePorUnidade: "500 g",
    dataValidade: "2026-10-05",
  },
  {
    codigo: "PRD-0412",
    nome: "Shampoo Anticaspa",
    categoria: "Higiene",
    fornecedor: "Beleza Natural",
    preco: "R$ 19,90",
    quantidadePorUnidade: "350 ml",
    dataValidade: "2027-08-12",
  },
  {
    codigo: "PRD-0520",
    nome: "Papel Higiênico 12 rolos",
    categoria: "Higiene",
    fornecedor: "SoftPaper",
    preco: "R$ 22,00",
    quantidadePorUnidade: "12 un.",
    dataValidade: "",
  },
  {
    codigo: "PRD-0633",
    nome: "Óleo de Soja 900ml",
    categoria: "Alimentos",
    fornecedor: "AgroBrasil",
    preco: "R$ 7,50",
    quantidadePorUnidade: "900 ml",
    dataValidade: "2026-09-18",
  },
  {
    codigo: "PRD-0744",
    nome: "Desinfetante Floral",
    categoria: "Limpeza",
    fornecedor: "Limpex",
    preco: "R$ 6,90",
    quantidadePorUnidade: "1 l",
    dataValidade: "2027-01-25",
  },
];
