spring.application.name=GestorX

# BANCO (Neon via variáveis de ambiente; padrão = Postgres local)
spring.datasource.url=${DB_URL:jdbc:postgresql://neondb_owner:npg_BI45bGwsvKZi@ep-purple-wave-b6f1i4th-pooler.c-2.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USER:usuario}
spring.datasource.password=${DB_PASSWORD:senha}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000

# HIBERNATE #
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect